const ProductDetailsActionsTypes = {
  FETCH_PRODUCT_DETAILS_START: 'FETCH_PRODUCT_DETAILS_START',
  FETCH_PRODUCT_DETAILS_SUCCESS: 'FETCH_PRODUCT_DETAILS_SUCCESS',
  FETCH_PRODUCT_DETAILS_FAILURE: 'FETCH_PRODUCT_DETAILS_FAILURE'
}

export default ProductDetailsActionsTypes