const ProductsActionTypes = {
  FETCH_PRODUCTS_START: 'FETCH_PRODUCTS_START',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
  FETCH_SINGLE_PRODUCT_START: 'FETCH_SINGLE_PRODUCT_START',
  FETCH_SINGLE_PRODUCT_SUCCESS: 'FETCH_SINGLE_PRODUCT_SUCCESS',
  FETCH_SINGLE_PRODUCT_FAILURE: 'FETCH_SINGLE_PRODUCT_FAILURE' 
}

export default ProductsActionTypes